import type { ProjectMeta } from "@/types/content";

export const projects: ProjectMeta[] = [
  {
    slug: "qlik-events",
    title: "Natural events claims monitoring",
    summary:
      "QlikSense dashboard to track volumes, costs and trends for natural events.",
    tags: ["BI", "QlikSense", "Insurance", "KPI"],
    featured: true,
    date: "2025-01-12",
    stack: ["QlikSense", "SQL", "Data Modeling", "KPI Design"],
    coverImage: "/images/projects/cover-analytics.svg",
    gallery: ["/images/projects/cover-analytics.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Multi-scope monitoring", "Critical KPIs consolidated"],
  },
  {
    slug: "qlik-provisions",
    title: "Claims provisions & recoveries",
    summary:
      "QlikSense reporting to visualize provisions, recoveries and budget trends.",
    tags: ["BI", "QlikSense", "Insurance"],
    featured: false,
    date: "2025-02-05",
    stack: ["QlikSense", "SQL", "Data Quality"],
    coverImage: "/images/projects/cover-analytics.svg",
    gallery: ["/images/projects/cover-analytics.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Variance analysis", "Budget steering"],
  },
  {
    slug: "powerbi-itsm",
    title: "ITSM: ticket trends & productivity",
    summary:
      "Power BI dashboard for ITSM performance, incidents, and agent productivity.",
    tags: ["BI", "Power BI", "ITSM"],
    featured: true,
    date: "2024-03-18",
    stack: ["Power BI", "DAX", "SQL", "Data Modeling"],
    coverImage: "/images/projects/cover-dashboard.svg",
    gallery: ["/images/projects/cover-dashboard.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Service desk KPIs", "Incident trends"],
  },
  {
    slug: "landside-cleaning",
    title: "Landside cleaning vendor",
    summary:
      "Bronze/silver/gold architecture and Dataiku + Azure pipelines for operations.",
    tags: ["Data Eng", "Dataiku", "Azure", "ETL"],
    featured: true,
    date: "2024-06-10",
    stack: ["Dataiku", "Azure", "SQL", "ETL"],
    coverImage: "/images/projects/cover-pipeline.svg",
    gallery: ["/images/projects/cover-pipeline.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Multi-zone pipeline", "Terminal 2F granularity"],
  },
  {
    slug: "incident-metrics",
    title: "Incident & ticket metrics optimization",
    summary:
      "Refined KPIs and visuals to accelerate operational decision-making.",
    tags: ["BI", "Power BI", "KPI"],
    featured: false,
    date: "2024-08-20",
    stack: ["Power BI", "DAX", "Data Modeling"],
    coverImage: "/images/projects/cover-dashboard.svg",
    gallery: ["/images/projects/cover-dashboard.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Clearer KPIs", "Faster decisions"],
  },
  {
    slug: "voice-of-people",
    title: "Voice of employees",
    summary:
      "Internal feedback synthesis to reveal trends and weak signals.",
    tags: ["BI", "Survey", "Insights"],
    featured: false,
    date: "2023-11-02",
    stack: ["Power BI", "Data Prep", "Text Insights"],
    coverImage: "/images/projects/cover-product.svg",
    gallery: ["/images/projects/cover-product.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Key themes", "Feedback mapping"],
  },
  {
    slug: "sig-app",
    title: "GIS app (Python + VueJS)",
    summary:
      "Map-based app to analyze territorial and business data.",
    tags: ["Python", "VueJS", "GIS"],
    featured: false,
    date: "2023-04-15",
    stack: ["Python", "VueJS", "Leaflet", "API"],
    coverImage: "/images/projects/cover-geo.svg",
    gallery: ["/images/projects/cover-geo.svg"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "lsf-ai",
    title: "AI accessibility app for sign language",
    summary:
      "Gesture recognition prototype to support LSF communication.",
    tags: ["AI", "OpenCV", "MediaPipe", "TensorFlow"],
    featured: true,
    date: "2023-09-05",
    stack: ["Python", "OpenCV", "MediaPipe", "TensorFlow"],
    coverImage: "/images/projects/cover-ai.svg",
    gallery: ["/images/projects/cover-ai.svg"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "social-generator",
    title: "Social post generator",
    summary:
      "React + FastAPI app to generate optimized posts from a brief.",
    tags: ["AI", "React", "FastAPI", "OpenAI"],
    featured: false,
    date: "2024-01-22",
    stack: ["React", "FastAPI", "OpenAI API"],
    coverImage: "/images/projects/cover-ai.svg",
    gallery: ["/images/projects/cover-ai.svg"],
    links: {},
    confidentiality: "public",
  }
];
