import type { ProjectMeta } from "@/types/content";

export const projects: ProjectMeta[] = [
  {
    slug: "sig-app",
    title: "GIS App (Python + VueJS)",
    summary:
      "Map-based application to analyze territorial and business data.",
    tags: ["Python", "VueJS", "GIS"],
    featured: true,
    date: "2023-04-15",
    stack: ["Python", "VueJS", "Leaflet", "API"],
    coverImage: "/images/projects/scapesig.png",
    gallery: ["/images/projects/scapesig.png"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "lsf-ai",
    title: "AI Accessibility App for Sign Language",
    summary:
      "Gesture recognition prototype to support French Sign Language communication.",
    tags: ["AI", "OpenCV", "MediaPipe", "TensorFlow"],
    featured: true,
    date: "2023-09-05",
    stack: ["Python", "OpenCV", "MediaPipe", "TensorFlow"],
    coverImage: "/images/projects/LSAII.gif",
    gallery: ["/images/projects/LSAII.gif"],
    links: {},
    confidentiality: "public",
    externalUrl: "https://www.linkedin.com/posts/activity-7201594993315041280-NTvc/",
  },
  {
    slug: "social-generator",
    title: "Imaginify – Social Media Post Generator",
    summary:
      "Full-stack React + FastAPI app to generate social media content (text + visuals) from a user brief.",
    tags: ["AI", "React", "FastAPI", "GenAI"],
    featured: true,
    date: "2023-06-15",
    stack: ["Python", "React", "FastAPI", "GenAI", "Docker"],
    coverImage: "/images/projects/imaginify.png",
    gallery: ["/images/projects/imaginify.png"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "sqte-website",
    title: "SQTE Association Website",
    summary:
      "Modern showcase website for the SQTE association, built with a focus on accessibility and user experience.",
    tags: ["Web", "React", "Next.js"],
    featured: true,
    date: "2024-06-10",
    stack: ["React", "Next.js", "Tailwind CSS"],
    coverImage: "/images/projects/sqte.png",
    gallery: ["/images/projects/sqte.png"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "factai",
    title: "FactAI – Content Reliability Checker",
    summary:
      "Automated analysis and fact-checking application. Accepts media files, YouTube URLs and other sources, extracts and transcribes content, structures information, then uses LLM APIs to verify the reliability of claims.",
    tags: ["AI", "LLM", "NLP", "Fact-checking"],
    featured: true,
    date: "2024-11-15",
    stack: ["React", "Python", "Flask", "Azure OpenAI", "Docker"],
    coverImage: "/images/projects/Factai_form.png",
    gallery: ["/images/projects/Factai_form.png"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "bi-dashboards",
    title: "BI / Data / Dashboard Projects",
    summary:
      "Collection of enterprise BI projects: QlikSense dashboards (claims monitoring, provisions), Power BI (ITSM, incidents), and data analysis (employee feedback). KPI design, data modeling and business visualizations.",
    tags: ["BI", "Power BI", "QlikSense", "Data"],
    featured: true,
    date: "2025-02-05",
    stack: ["Power BI", "QlikSense", "DAX", "SQL", "Data Modeling"],
    coverImage: "/images/projects/pilotage_sinistre.png",
    gallery: [
      "/images/projects/pilotage_sinistre.png",
      "/images/projects/pbi.png",
    ],
    links: {},
    confidentiality: "sanitized",
    metrics: [
      "Multi-scope dashboards",
      "Consolidated KPIs",
      "Budget steering",
    ],
  },
  {
    slug: "radar-prediction",
    title: "Radar Data Prediction",
    summary:
      "Interactive application displaying a map of France with speed cameras, speed data and predictions.",
    tags: ["Data", "Python", "Map", "ML"],
    featured: true,
    date: "2024-09-01",
    stack: ["Python", "Leaflet", "Machine Learning", "API"],
    coverImage: "/images/projects/cover-analytics.svg",
    gallery: ["/images/projects/cover-analytics.svg"],
    links: {},
    confidentiality: "public",
  },
];
