import type { ProjectMeta } from "@/types/content";

export const projects: ProjectMeta[] = [
  {
    slug: "qlik-events",
    title: "Pilotage sinistres « événements naturels »",
    summary:
      "Tableau de bord QlikSense pour suivre volumes, coûts et tendances liées aux événements naturels.",
    tags: ["BI", "QlikSense", "Assurance", "KPI"],
    featured: true,
    date: "2025-01-12",
    stack: ["QlikSense", "SQL", "Data Modeling", "KPI Design"],
    coverImage: "/images/projects/cover-analytics.svg",
    gallery: ["/images/projects/cover-analytics.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Suivi multi-périmètre", "Indicateurs critiques consolidés"],
  },
  {
    slug: "qlik-provisions",
    title: "Pilotage provisions & recours sinistres",
    summary:
      "Reporting QlikSense pour visualiser provisions, recours et trajectoires budgétaires.",
    tags: ["BI", "QlikSense", "Assurance"],
    featured: false,
    date: "2025-02-05",
    stack: ["QlikSense", "SQL", "Data Quality"],
    coverImage: "/images/projects/cover-analytics.svg",
    gallery: ["/images/projects/cover-analytics.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Analyse des écarts", "Pilotage budgétaire"],
  },
  {
    slug: "powerbi-itsm",
    title: "ITSM : tickets trend & productivité",
    summary:
      "Dashboard Power BI pour la performance ITSM, incidents et productivité agents.",
    tags: ["BI", "Power BI", "ITSM"],
    featured: true,
    date: "2024-03-18",
    stack: ["Power BI", "DAX", "SQL", "Data Modeling"],
    coverImage: "/images/projects/cover-dashboard.svg",
    gallery: ["/images/projects/cover-dashboard.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["KPIs service desk", "Tendances incidents"],
  },
  {
    slug: "landside-cleaning",
    title: "Prestataire nettoyage Landside",
    summary:
      "Architecture bronze/silver/gold et pipelines Dataiku + Azure pour un suivi opérationnel.",
    tags: ["Data Eng", "Dataiku", "Azure", "ETL"],
    featured: true,
    date: "2024-06-10",
    stack: ["Dataiku", "Azure", "SQL", "ETL"],
    coverImage: "/images/projects/cover-pipeline.svg",
    gallery: ["/images/projects/cover-pipeline.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Pipeline multi-zones", "Granularité terminal 2F"],
  },
  {
    slug: "incident-metrics",
    title: "Optimisation métriques incidents & tickets",
    summary:
      "Rationalisation des indicateurs et visualisations pour accélérer la décision.",
    tags: ["BI", "Power BI", "KPI"],
    featured: false,
    date: "2024-08-20",
    stack: ["Power BI", "DAX", "Data Modeling"],
    coverImage: "/images/projects/cover-dashboard.svg",
    gallery: ["/images/projects/cover-dashboard.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Meilleure lisibilité", "Décision plus rapide"],
  },
  {
    slug: "voice-of-people",
    title: "Voix des collaborateurs",
    summary:
      "Synthèse des feedbacks internes pour détecter tendances et signaux faibles.",
    tags: ["BI", "Survey", "Insights"],
    featured: false,
    date: "2023-11-02",
    stack: ["Power BI", "Data Prep", "Text Insights"],
    coverImage: "/images/projects/cover-product.svg",
    gallery: ["/images/projects/cover-product.svg"],
    links: {},
    confidentiality: "sanitized",
    metrics: ["Thématiques clés", "Cartographie des retours"],
  },
  {
    slug: "sig-app",
    title: "App SIG (Python + VueJS)",
    summary:
      "Application cartographique pour analyser des données territoriales et métiers.",
    tags: ["Python", "VueJS", "GIS"],
    featured: false,
    date: "2023-04-15",
    stack: ["Python", "VueJS", "Leaflet", "API"],
    coverImage: "/images/projects/cover-geo.svg",
    gallery: ["/images/projects/cover-geo.svg"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "lsf-ai",
    title: "App accessibilité IA LSF",
    summary:
      "Prototype de reconnaissance gestuelle pour faciliter la communication en LSF.",
    tags: ["IA", "OpenCV", "MediaPipe", "TensorFlow"],
    featured: true,
    date: "2023-09-05",
    stack: ["Python", "OpenCV", "MediaPipe", "TensorFlow"],
    coverImage: "/images/projects/cover-ai.svg",
    gallery: ["/images/projects/cover-ai.svg"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "social-generator",
    title: "Générateur de posts réseaux sociaux",
    summary:
      "App React + FastAPI pour générer des posts optimisés à partir d’un brief.",
    tags: ["IA", "React", "FastAPI", "OpenAI"],
    featured: false,
    date: "2024-01-22",
    stack: ["React", "FastAPI", "OpenAI API"],
    coverImage: "/images/projects/cover-ai.svg",
    gallery: ["/images/projects/cover-ai.svg"],
    links: {},
    confidentiality: "public",
  }
];
