import type { ProjectMeta } from "@/types/content";

export const projects: ProjectMeta[] = [
  {
    slug: "sig-app",
    title: "App SIG (Système d'Information Géographique)",
    summary:
      "Application cartographique pour analyser des données territoriales et métiers.",
    tags: ["Python", "VueJS", "GIS"],
    featured: true,
    date: "2023-04-15",
    stack: ["Python", "VueJS", "Leaflet", "API"],
    coverImage: "/images/projects/scapesig.png",
    gallery: ["/images/projects/scapesig.png"],
    links: {},
    confidentiality: "public",
    externalUrl: "https://github.com/Khaldi-o",
  },
  {
    slug: "lsf-ai",
    title: "App accessibilité IA LSF",
    summary:
      "Prototype de reconnaissance gestuelle pour faciliter la communication en Langue des Signes Française.",
    tags: ["IA", "OpenCV", "MediaPipe", "TensorFlow"],
    featured: true,
    date: "2023-09-05",
    stack: ["Python", "OpenCV", "MediaPipe", "TensorFlow"],
    coverImage: "/images/projects/LSAII.gif",
    gallery: ["/images/projects/LSAII.gif"],
    links: {},
    confidentiality: "public",
    externalUrl: "https://www.linkedin.com/posts/activity-7201594993315041280-NTvc/",
  },
  {
    slug: "social-generator",
    title: "Imaginify",
    summary:
      "App fullstack pour générer du contenu réseaux sociaux (texte + visuels) à partir d'un brief utilisateur.",
    tags: ["IA", "React", "FastAPI", "GenAI"],
    featured: true,
    date: "2023-06-15",
    stack: ["Python", "React", "FastAPI", "GenAI", "Docker"],
    coverImage: "/images/projects/imaginify.png",
    gallery: ["/images/projects/imaginify.png"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "sqte-website",
    title: "SQTE",
    summary:
      "Site vitrine moderne développé pour l'association SQTE.",
    tags: ["Web", "React", "Next.js"],
    featured: true,
    date: "2024-06-10",
    stack: ["React", "Next.js", "Tailwind CSS"],
    coverImage: "/images/projects/sqte.png",
    gallery: ["/images/projects/sqte.png"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "factai",
    title: "FactAI",
    summary:
      "Application de Fact-Checking, qui extrait et transcrit des contenus (PDF, audio, vidéo, YouTube), structure l’information et utilise des APIs LLM pour en vérifier la fiabilité.",
    tags: ["IA", "LLM", "NLP", "Fact-checking"],
    featured: true,
    date: "2024-11-15",
    stack: ["React", "Python", "Flask", "Azure OpenAI", "Docker"],
    coverImage: "/images/projects/Factai_form.png",
    gallery: ["/images/projects/Factai_form.png"],
    links: {},
    confidentiality: "public",
  },
  {
    slug: "bi-dashboards",
    title: "Projets BI / Data / Dashboards",
    summary:
      "Ensemble de projets BI réalisés en entreprise : dashboards QlikSense (pilotage sinistres, provisions), Power BI (ITSM, incidents), et analyses data (feedbacks collaborateurs). Conception de KPIs, data modeling et visualisations métier.",
    tags: ["BI", "Power BI", "QlikSense", "Data"],
    featured: true,
    date: "2025-02-05",
    stack: ["Power BI", "QlikSense", "DAX", "SQL", "Data Modeling"],
    coverImage: "/images/projects/pilotage_sinistre.png",
    gallery: [
      "/images/projects/pilotage_sinistre.png",
      "/images/projects/pbi.png",
    ],
    links: {},
    confidentiality: "sanitized",
    metrics: [
      "Dashboards multi-périmètres",
      "KPIs consolidés",
      "Pilotage budgétaire",
    ],
  },
  {
    slug: "radar-prediction",
    title: "Radar Data Prediction",
    summary:
      "Application affichant une carte de France interactive avec les radars, les vitesses et des prédictions basées sur les données.",
    tags: ["Data", "Python", "Map", "ML"],
    featured: true,
    date: "2024-09-01",
    stack: ["Python", "Leaflet", "Machine Learning", "API"],
    coverImage: "/images/projects/cover-analytics.svg",
    gallery: ["/images/projects/cover-analytics.svg"],
    links: {},
    confidentiality: "public",
    externalUrl: "https://github.com/Khaldi-o",
  },
];
